### ISSUE TITLE
Loading Mixed Case Memory Mounted Files Fails With 404

### ISSUE THREAD

**Issue by palobby** [UberEnt/pa-ui#26]
- loading of mixed case memory mounted files fails with 404

Unlike the file system, memory mounted paths and filenames are forced to lowercase.

Many mods using mixed case paths or filenames that previously worked via file system fail with 404s when loaded using any of the following:
- loadSceneMods
- loadScript
- loadHtml
- loadCss
- $.get
- $.getJSON
- $.getScript
- XMLHttpRequest
- etc

A simple engine work around would be to retry with lowercase if the following apply:
- 404
- mixed case path or filename
- lowercase version exists in memory

**Comment by pinbender** [comment]
is this still an issue on the latest PTE?

**Comment by palobby** [comment]
Fixed in PTE... closing.
